export { default as HomeSvg } from './HomeSvg'
export { default as SearchSvg } from './SearchSvg'
export { default as PodcastSvg } from './PodcastSvg'
export { default as PlaySvg } from './PlaySvg'
export { default as PauseSvg } from './PauseSvg'
export { default as VolumeSvg } from './VolumeSvg'
export { default as PodcastIllustrationSvg } from './PodcastIllustrationSvg'
